apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-test-svc-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-test-svc-app
  template:
    metadata:
      labels:
        app: nodejs-test-svc-app
    spec:
      containers:
        - name: nodejs-test-svc-app-image
          image: gcr.io/$GCLOUD_PROJECT_ID/nodejs-test-svc-app-image:latest
          imagePullPolicy: "Always"
          env:
            - name: "PORT"
              value: "5010"
