apiVersion: v1
kind: Service
metadata:
  name: nodejs-test-svc-app-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-test-svc-app
  ports:
    - protocol: "TCP"
      port: 60000
      targetPort: 5010
