apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-testsvc-app-service
spec:
  type: LoadBalancer
  selector:
    app: dotnetcore-testsvc-app
  ports:
    - protocol: "TCP"
      port: 60000
      targetPort: 5000
